### ISSUE TITLE
FindMergeCommits bug

### ISSUE THREAD

**Issue by benedikt-schesch** [benedikt-schesch/AST-Merging-Evaluation#108]
There is a bug current on the main branch with FindMergeCommits. The following error is raised when running run_full.sh
```
Exception in thread "main" java.lang.Error: java.lang.Error: java.lang.Error: Histories are unrelated for getMergeBaseCommit(Repository[/tmp/scheschb/ast-merge-eval-data/jlinn__quartz-redis-jobstore], commit d215c1856fe1b0dd7cba46f4cece5e1c20fc1d5e 1406072839 -----sp, commit 191d82f0448bf895e370618354d696000e66c4c9 1406072846 -----sp)
Finding merge commits for AlbinTheander/MeQanTT             DONE
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
        at astmergeevaluation.FindMergeCommits.writeMergeCommitsForRepos(FindMergeCommits.java:192)
        at astmergeevaluation.FindMergeCommits.main(FindMergeCommits.java:105)
Caused by: java.lang.Error: java.lang.Error: Histories are unrelated for getMergeBaseCommit(Repository[/tmp/scheschb/ast-merge-eval-data/jlinn__quartz-redis-jobstore], commit d215c1856fe1b0dd7cba46f4cece5e1c20fc1d5e 1406072839 -----sp, commit 191d82f0448bf895e370618354d696000e66c4c9 1406072846 -----sp)
        at astmergeevaluation.FindMergeCommits.writeMergeCommitsForRepo(FindMergeCommits.java:210)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.Error: Histories are unrelated for getMergeBaseCommit(Repository[/tmp/scheschb/ast-merge-eval-data/jlinn__quartz-redis-jobstore], commit d215c1856fe1b0dd7cba46f4cece5e1c20fc1d5e 1406072839 -----sp, commit 191d82f0448bf895e370618354d696000e66c4c9 1406072846 -----sp)
```

**Comment by benedikt-schesch** [comment]
This seems to be fixed, I'll close it when I manage to finish running the entire script with no issue
